/* eslint-disable prettier/prettier */
export enum NotificationEventType {
  FOLLOWED = 'FOLLOWED',
  POST_LIKED = 'POST_LIKED',
  POST_COMMENTED = 'POST_COMMENTED',
  MESSAGE_SENT = 'MESSAGE_SENT',

  PROFILE_VIEWED = 'PROFILE_VIEWED',
  INTENT_OVERLAP = 'INTENT_OVERLAP',
  SKILL_MATCH = 'SKILL_MATCH',
}
