### 1️⃣Register a New Institution
POST http://localhost:3000/institutions/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc2NDg3NjcxNywiZXhwIjoxNzY0OTYzMTE3fQ.N7uj8ahZ5rVnkv_qryFfx400kSv4tvQG9KoItxFlzkk
Content-Type: application/json

{
  "name": "Lukenya University",
  "description": "Testing institution registration",
  "officialEmail": "lukenya@lukenya.ac.ke",
  "websiteUrl": "https://www.lukenya.ac.ke",
  "officialDomain": "lukenya.ac.ke"
}

### Update Institution Status (Super Admin)
PATCH http://localhost:3000/institutions/8d514992-5558-4db5-a1a1-d2bd516b89da/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTdkZjkxOC1lZmViLTQ2YTUtYWYzMC05M2MwYTUyYjdjM2UiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjQ4NzY4NTksImV4cCI6MTc2NDk2MzI1OX0.KoF1BeDKaJRRTfA84pFrkakU76m9P-jU5AmP3R9N2Dk
Content-Type: application/json

{
  "status": "APPROVED",
  "reviewedById": "b17df918-efeb-46a5-af30-93c0a52b7c3e"
}

### Assign Admin to Institution
POST http://localhost:3000/institutions/60c87c6f-595a-4406-81b2-59f6bb0e270c/assign-admin/9be5bf48-3343-4ad3-8706-d25a939ca7ed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMjhlZWNjMS01MmMwLTQzODQtYmI2My1jMmUxYWIxMmQzZTEiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpQGdtYWlsLmNvbSIsInJvbGUiOiJJTlNUSVRVVElPTl9BRE1JTiIsImlhdCI6MTc1ODIyMzU0MCwiZXhwIjoxNzU4MzA5OTQwfQ.Qstuj9m5xcLZnBbjpTa_hyLwRA-lINCeWeULc2E7ITU
Content-Type: application/json

### Create an Invite
POST http://localhost:3000/institutions/{{INSTITUTION_ID}}/invite
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: application/json

{
  "email": "newadmin@example.com"
}

### Consume Invite Token
POST http://localhost:3000/institutions/consume-invite/{{INVITE_TOKEN}}
Authorization: Bearer {{JWT_TOKEN}}

### Create Announcement (with files)
POST http://localhost:3000/institutions/60c87c6f-595a-4406-81b2-59f6bb0e270c/announcement
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMjhlZWNjMS01MmMwLTQzODQtYmI2My1jMmUxYWIxMmQzZTEiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpQGdtYWlsLmNvbSIsInJvbGUiOiJJTlNUSVRVVElPTl9BRE1JTiIsImlhdCI6MTc1ODIyMzU0MCwiZXhwIjoxNzU4MzA5OTQwfQ.Qstuj9m5xcLZnBbjpTa_hyLwRA-lINCeWeULc2E7ITU
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="title"

New Exam Schedule
--WebAppBoundary
Content-Disposition: form-data; name="content"

true
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="file1.pdf"
Content-Type: application/pdf

< ./path/to/file1.pdf
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="file2.png"
Content-Type: image/png

< ./path/to/file2.png
--WebAppBoundary--

### 6️⃣ Update Announcement (with optional new files)
PATCH http://localhost:3000/institutions/announcements/b4fe552d-e71f-4029-a581-0aeea8b20ca2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMjhlZWNjMS01MmMwLTQzODQtYmI2My1jMmUxYWIxMmQzZTEiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpQGdtYWlsLmNvbSIsInJvbGUiOiJJTlNUSVRVVElPTl9BRE1JTiIsImlhdCI6MTc1ODIyMzU0MCwiZXhwIjoxNzU4MzA5OTQwfQ.Qstuj9m5xcLZnBbjpTa_hyLwRA-lINCeWeULc2E7ITU
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="title"

New Exam Schedule
--WebAppBoundary
Content-Disposition: form-data; name="content"

true
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="file1.pdf"
Content-Type: application/pdf

< ./path/to/file1.pdf
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="file2.png"
Content-Type: image/png

< ./path/to/file2.png
--WebAppBoundary--

### 7️⃣ Delete Announcement
DELETE http://localhost:3000/institutions/announcements/{{ANNOUNCEMENT_ID}}
Authorization: Bearer {{JWT_TOKEN}}

### Get Institution Analytics
GET http://localhost:3000/institutions/60c87c6f-595a-4406-81b2-59f6bb0e270c/analytics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMjhlZWNjMS01MmMwLTQzODQtYmI2My1jMmUxYWIxMmQzZTEiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpQGdtYWlsLmNvbSIsInJvbGUiOiJJTlNUSVRVVElPTl9BRE1JTiIsImlhdCI6MTc1ODIyMzU0MCwiZXhwIjoxNzU4MzA5OTQwfQ.Qstuj9m5xcLZnBbjpTa_hyLwRA-lINCeWeULc2E7ITU


### Get Admin's Announcements
GET http://localhost:3000/institutions/my-announcements
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmU1YmY0OC0zMzQzLTRhZDMtODcwNi1kMjVhOTM5Y2E3ZWQiLCJlbWFpbCI6ImoyNjUxNTc2MkBnbWFpbC5jb20iLCJyb2xlIjoiSU5TVElUVVRJT05fQURNSU4iLCJpYXQiOjE3NTgyNjI3MTIsImV4cCI6MTc1ODM0OTExMn0.rytdCtFOpe-Oc_yTopUq8YKov_Dp_Tnk63kQ-YJmLcM


### Get single announcement by ID (with metadata) 
GET http://localhost:3000/institutions/b4fe552d-e71f-4029-a581-0aeea8b20ca2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmU1YmY0OC0zMzQzLTRhZDMtODcwNi1kMjVhOTM5Y2E3ZWQiLCJlbWFpbCI6ImoyNjUxNTc2MkBnbWFpbC5jb20iLCJyb2xlIjoiSU5TVElUVVRJT05fQURNSU4iLCJpYXQiOjE3NTgyNjI3MTIsImV4cCI6MTc1ODM0OTExMn0.rytdCtFOpe-Oc_yTopUq8YKov_Dp_Tnk63kQ-YJmLcM


### Get Institution Analytics
GET http://localhost:3000/institutions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmU1YmY0OC0zMzQzLTRhZDMtODcwNi1kMjVhOTM5Y2E3ZWQiLCJlbWFpbCI6ImoyNjUxNTc2MkBnbWFpbC5jb20iLCJyb2xlIjoiSU5TVElUVVRJT05fQURNSU4iLCJpYXQiOjE3NTgzMTc1MDUsImV4cCI6MTc1ODQwMzkwNX0.YIv5CGCSGJJSBjkRylWI8cJHM9_hKmuteerlGSnv3lc

###
GET http://localhost:3000/institutions/approved
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc2NDg3NjcxNywiZXhwIjoxNzY0OTYzMTE3fQ.N7uj8ahZ5rVnkv_qryFfx400kSv4tvQG9KoItxFlzkk
Content-Type: application/json