# get all groups
GET  http://localhost:3000/admin/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTdkZjkxOC1lZmViLTQ2YTUtYWYzMC05M2MwYTUyYjdjM2UiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjMxNDE0MzAsImV4cCI6MTc2MzIyNzgzMH0.JXhQ8IswkzyfxoVk4KWxq4SMNXozOMAk8_M1Kunc7dg

###
# Get members of a specific group
GET  http://localhost:3000/admin/groups/ddfb1e70-c3ac-4c7d-b25a-9d875b21105c/members
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTdkZjkxOC1lZmViLTQ2YTUtYWYzMC05M2MwYTUyYjdjM2UiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjMxNDE0MzAsImV4cCI6MTc2MzIyNzgzMH0.JXhQ8IswkzyfxoVk4KWxq4SMNXozOMAk8_M1Kunc7dg

### 
# Soft-delete a group
DELETE  http://localhost:3000/admin/groups/501c3b00-7e5d-4716-90a5-a787c0cdb740
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTdkZjkxOC1lZmViLTQ2YTUtYWYzMC05M2MwYTUyYjdjM2UiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjMwMzI0OTcsImV4cCI6MTc2MzExODg5N30.eAYdbuzVYiiSJv5jqKK4rJnWZ_7GFoQSMCeegsGlEhc
###
# Restore a soft-deleted group
PATCH  http://localhost:3000/admin/groups/:id/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTdkZjkxOC1lZmViLTQ2YTUtYWYzMC05M2MwYTUyYjdjM2UiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjMwMzI0OTcsImV4cCI6MTc2MzExODg5N30.eAYdbuzVYiiSJv5jqKK4rJnWZ_7GFoQSMCeegsGlEhc
