### get all users
GET http://localhost:3000/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTdkZjkxOC1lZmViLTQ2YTUtYWYzMC05M2MwYTUyYjdjM2UiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTg3NDUxNDEsImV4cCI6MTc1ODgzMTU0MX0.9KLSiAsVuMK-atrjS5-0jcn5u8U3ltEobA_akNdKM0I

### get a user by id
GET http://localhost:3000/admin/users/146ba0b7-e513-418d-89dd-539ffec59a04
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTdkZjkxOC1lZmViLTQ2YTUtYWYzMC05M2MwYTUyYjdjM2UiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTU1ODA5NDEsImV4cCI6MTc1NTY2NzM0MX0.WT187Uq4ZdIlPNv-1SghkROKCImGM5ZNMvtZjsfRjao

### update a user
PATCH http://localhost:3000/admin/users/9be5bf48-3343-4ad3-8706-d25a939ca7ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTdkZjkxOC1lZmViLTQ2YTUtYWYzMC05M2MwYTUyYjdjM2UiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTU1ODA5NDEsImV4cCI6MTc1NTY2NzM0MX0.WT187Uq4ZdIlPNv-1SghkROKCImGM5ZNMvtZjsfRjao

{
  "name": "Edison Mark"
}

### delete a user
DELETE http://localhost:3000/admin/users/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTdkZjkxOC1lZmViLTQ2YTUtYWYzMC05M2MwYTUyYjdjM2UiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTU1ODA5NDEsImV4cCI6MTc1NTY2NzM0MX0.WT187Uq4ZdIlPNv-1SghkROKCImGM5ZNMvtZjsfRjao


### suspend a user
PATCH http://localhost:3000/admin/users/9be5bf48-3343-4ad3-8706-d25a939ca7ed/suspend
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTdkZjkxOC1lZmViLTQ2YTUtYWYzMC05M2MwYTUyYjdjM2UiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTU1ODA5NDEsImV4cCI6MTc1NTY2NzM0MX0.WT187Uq4ZdIlPNv-1SghkROKCImGM5ZNMvtZjsfRjao


### restore a suspended user
PATCH http://localhost:3000/admin/users/9be5bf48-3343-4ad3-8706-d25a939ca7ed/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTdkZjkxOC1lZmViLTQ2YTUtYWYzMC05M2MwYTUyYjdjM2UiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTU1ODA5NDEsImV4cCI6MTc1NTY2NzM0MX0.WT187Uq4ZdIlPNv-1SghkROKCImGM5ZNMvtZjsfRjao

### mass suspend user
PATCH http://localhost:3000/admin/users/suspend
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTdkZjkxOC1lZmViLTQ2YTUtYWYzMC05M2MwYTUyYjdjM2UiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTU1ODA5NDEsImV4cCI6MTc1NTY2NzM0MX0.WT187Uq4ZdIlPNv-1SghkROKCImGM5ZNMvtZjsfRjao
Content-Type: application/json

{
  "ids": [
    "146ba0b7-e513-418d-89dd-539ffec59a04",
    "9be5bf48-3343-4ad3-8706-d25a939ca7ed"
  ]
}

### mass restore suspended users
PATCH http://localhost:3000/admin/users/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTdkZjkxOC1lZmViLTQ2YTUtYWYzMC05M2MwYTUyYjdjM2UiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTU1ODA5NDEsImV4cCI6MTc1NTY2NzM0MX0.WT187Uq4ZdIlPNv-1SghkROKCImGM5ZNMvtZjsfRjao
Content-Type: application/json

{
  "ids": [
    "146ba0b7-e513-418d-89dd-539ffec59a04",
    "9be5bf48-3343-4ad3-8706-d25a939ca7ed"
  ]
}