### Like a comment
POST http://localhost:3000/comment-like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjQ2OTA4My1mNTM0LTQxZDItODE3Ni1jMWIxMDdlYzNjNjMiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpMTZAZ21haWwuY29tIiwicm9sZSI6IlNUVURFTlQiLCJpYXQiOjE3NTM0MDExMzUsImV4cCI6MTc1MzQ4NzUzNX0.Snp_mWhI_0PucFIGgEiFaMdjeaGTy5jMv9Q07SzMPoc
Content-Type: application/json


{
  "commentId": "8401b2ac-b810-4c40-8efd-c66b0b8ba67b"
}

### Get all likes for a comment
GET http://localhost:3000/comment-like/8401b2ac-b810-4c40-8efd-c66b0b8ba67b/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjQ2OTA4My1mNTM0LTQxZDItODE3Ni1jMWIxMDdlYzNjNjMiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpMTZAZ21haWwuY29tIiwicm9sZSI6IlNUVURFTlQiLCJpYXQiOjE3NTM0MDExMzUsImV4cCI6MTc1MzQ4NzUzNX0.Snp_mWhI_0PucFIGgEiFaMdjeaGTy5jMv9Q07SzMPoc
Content-Type: application/json


### Get total like count for a comment
GET http://localhost:3000/comment-like/8401b2ac-b810-4c40-8efd-c66b0b8ba67b/likes/count
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjQ2OTA4My1mNTM0LTQxZDItODE3Ni1jMWIxMDdlYzNjNjMiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpMTZAZ21haWwuY29tIiwicm9sZSI6IlNUVURFTlQiLCJpYXQiOjE3NTM0MDExMzUsImV4cCI6MTc1MzQ4NzUzNX0.Snp_mWhI_0PucFIGgEiFaMdjeaGTy5jMv9Q07SzMPoc
Content-Type: application/json
