### follow a user
POST http://localhost:3000/follow/b17df918-efeb-46a5-af30-93c0a52b7c3e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmU1YmY0OC0zMzQzLTRhZDMtODcwNi1kMjVhOTM5Y2E3ZWQiLCJlbWFpbCI6ImoyNjUxNTc2MkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1MzM3OTA2NywiZXhwIjoxNzUzNDY1NDY3fQ.gqPpJWBG_Xvxojh8k43Ts5npDHRE58u-PWPFu9q74FE

### unfollow a user
DELETE http://localhost:3000/follow/e160b889-e31c-43e1-858d-478aa413842a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmU1YmY0OC0zMzQzLTRhZDMtODcwNi1kMjVhOTM5Y2E3ZWQiLCJlbWFpbCI6ImoyNjUxNTc2MkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1MzM3OTA2NywiZXhwIjoxNzUzNDY1NDY3fQ.gqPpJWBG_Xvxojh8k43Ts5npDHRE58u-PWPFu9q74FE

### see user's followers
GET http://localhost:3000/follow/followers/146ba0b7-e513-418d-89dd-539ffec59a04
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmU1YmY0OC0zMzQzLTRhZDMtODcwNi1kMjVhOTM5Y2E3ZWQiLCJlbWFpbCI6ImoyNjUxNTc2MkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1MzM3OTA2NywiZXhwIjoxNzUzNDY1NDY3fQ.gqPpJWBG_Xvxojh8k43Ts5npDHRE58u-PWPFu9q74FE


### see who a user is following
GET http://localhost:3000/follow/following/9be5bf48-3343-4ad3-8706-d25a939ca7ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmU1YmY0OC0zMzQzLTRhZDMtODcwNi1kMjVhOTM5Y2E3ZWQiLCJlbWFpbCI6ImoyNjUxNTc2MkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1MzM3OTA2NywiZXhwIjoxNzUzNDY1NDY3fQ.gqPpJWBG_Xvxojh8k43Ts5npDHRE58u-PWPFu9q74FE
