### follow a user
POST http://localhost:3000/follow/76469083-f534-41d2-8176-c1b107ec3c63
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1Mzc2OTk0MywiZXhwIjoxNzUzODU2MzQzfQ.IKW59LYUEkQVSQpzJnnQnipmnzpcCVcXjbpEObI49j0

### unfollow a user
DELETE http://localhost:3000/follow/e160b889-e31c-43e1-858d-478aa413842a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmU1YmY0OC0zMzQzLTRhZDMtODcwNi1kMjVhOTM5Y2E3ZWQiLCJlbWFpbCI6ImoyNjUxNTc2MkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1NDA3MDA5NSwiZXhwIjoxNzU0MTU2NDk1fQ.DWDSXlh0rW-7hraInAuZ1S5rGGJNGbMjQHT1k8JXRCM

### see user's followers
GET http://localhost:3000/follow/followers/146ba0b7-e513-418d-89dd-539ffec59a04
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc2NzA1MjA4MCwiZXhwIjoxNzY3MTM4NDgwfQ.3UlOFgGjx2QlTMx8RHeSf9pGkv7WcCHxlmvo5SCPrFM


### see who a user is following
GET http://localhost:3000/follow/following/9be5bf48-3343-4ad3-8706-d25a939ca7ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc2NzA1MjA4MCwiZXhwIjoxNzY3MTM4NDgwfQ.3UlOFgGjx2QlTMx8RHeSf9pGkv7WcCHxlmvo5SCPrFM

### get follow stats
GET http://localhost:3000/follow/76469083-f534-41d2-8176-c1b107ec3c63/stats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1NDY3OTA3OSwiZXhwIjoxNzU0NzY1NDc5fQ.GwnyL6roBBHnfQ2gIZPK3uofAqcQzPMiLmAG9Neuwu8


###
GET http://localhost:3000/follow/146ba0b7-e513-418d-89dd-539ffec59a04
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1NDY3ODcwMSwiZXhwIjoxNzU0NzY1MTAxfQ.x_RZeE2k8u88mim52Atd2C6ulvXnhNrkZfKOToWthnY