
@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc2NzgxNjUyMiwiZXhwIjoxNzY3OTAyOTIyfQ.Xryj5kPaGRWfzzqyvBW99uXv4R_4jcRtQa8iljFnWy4


### Create a 1:1 conversation (A chatting with B)
POST http://localhost:3000/conversations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmU1YmY0OC0zMzQzLTRhZDMtODcwNi1kMjVhOTM5Y2E3ZWQiLCJlbWFpbCI6ImoyNjUxNTc2MkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1NzM3MzY5MywiZXhwIjoxNzU3NDYwMDkzfQ.0imxrUkDPHPB3kuWsh-Fg1R08k_-MqWEFzPrnL4-QPA
Content-Type: application/json

{
  "participantIds": ["146ba0b7-e513-418d-89dd-539ffec59a04"]
}


### List all conversations for current user
GET http://localhost:3000/conversations
Authorization: Bearer {{jwtToken}}

### Get messages (latest 50) in a conversation
GET http://localhost:3000/conversations/5e69b167-359a-4a33-b3f9-102657179c6a/messages?limit=50
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1Nzk2NTIyMCwiZXhwIjoxNzU4MDUxNjIwfQ.r12hdHzI27fMfMt7wE_tk2oRZPqS0m3h9DBz6lgfKWU


### Send a message in conversation
POST http://localhost:3000/conversations/5e69b167-359a-4a33-b3f9-102657179c6a/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmU1YmY0OC0zMzQzLTRhZDMtODcwNi1kMjVhOTM5Y2E3ZWQiLCJlbWFpbCI6ImoyNjUxNTc2MkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1NzM3MzY5MywiZXhwIjoxNzU3NDYwMDkzfQ.0imxrUkDPHPB3kuWsh-Fg1R08k_-MqWEFzPrnL4-QPA
Content-Type: application/json

{
  "content": "Hey Edison 👋, testing our new chat!"
}


### Send a direct message by recipientId (backend will create or reuse convo)
POST http://localhost:3000/conversations/5e69b167-359a-4a33-b3f9-102657179c6a/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmU1YmY0OC0zMzQzLTRhZDMtODcwNi1kMjVhOTM5Y2E3ZWQiLCJlbWFpbCI6ImoyNjUxNTc2MkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1NzM3MzY5MywiZXhwIjoxNzU3NDYwMDkzfQ.0imxrUkDPHPB3kuWsh-Fg1R08k_-MqWEFzPrnL4-QPA
Content-Type: application/json

{
  "recipientId": "76469083-f534-41d2-8176-c1b107ec3c63",
  "content": "How are you doing today?!"
}


### Mark conversation as read
POST http://localhost:3000/conversations/{{CONV_ID}}/read
Authorization: Bearer {{ATOKEN}}


### Try to access conversation where user is NOT a participant Negative test (not participant)
GET http://localhost:3000/conversations/{{OTHER_CONV_ID}}/messages
Authorization: Bearer {{ATOKEN}}
