### Create a Post
POST http://localhost:3000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1MzU3MjkxMCwiZXhwIjoxNzUzNjU5MzEwfQ.uTdgUX6gV1UnpgNSO-32VIIyqxuSF5Gk8JXwFIlitFk
Content-Type: application/json

{
  "title": "Achieving Full Stack Mastery",
  "body": "My experience at Academeet has been transformative and rewarding.",
  "tags": ["postgresql", "tailwindcss", "nodejs"],
  "fileUrl": "https://res.cloudinary.com/yourcloud/image/upload/v1699999999/project-milestone.jpg"
}


### Get All Posts
GET http://localhost:3000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1MzcyODEwNCwiZXhwIjoxNzUzODE0NTA0fQ.zmMIyWZktqNE9APFpqVicCISbJ6xeEuEMqAd-rXzy6Y
Content-Type: application/json

### Get a Post by ID
GET http://localhost:3000/post/80cf419d-6db0-47a0-a214-441e23bda4c4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1NDUwNTE3MSwiZXhwIjoxNzU0NTkxNTcxfQ.82eia1TNhafaRiQrTh2wlYoGsyuYSpCS6RsYft8o0XE
Content-Type: application/json


### Update a Post by ID
PATCH http://localhost:3000/post/40865a03-f06e-4f19-ac5e-9b55f354ea9e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjQ2OTA4My1mNTM0LTQxZDItODE3Ni1jMWIxMDdlYzNjNjMiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpMTZAZ21haWwuY29tIiwicm9sZSI6IlNUVURFTlQiLCJpYXQiOjE3NTM0Nzc5MDEsImV4cCI6MTc1MzU2NDMwMX0.spPj2NFobTNZtkijPnv2Vh98NyIpj9pe_328XJqlEqk
Content-Type: application/json

{
  "title": "Updated Post Title",
  "body": "Updated content goes here.",
  "tags": ["backend", "nestjs"],
  "fileUrl": "https://res.cloudinary.com/demo/image/upload/v1234567890/updated.jpg"
}

### Delete a Post by ID
DELETE http://localhost:3000/post/abc123-post-id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjQ2OTA4My1mNTM0LTQxZDItODE3Ni1jMWIxMDdlYzNjNjMiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpMTZAZ21haWwuY29tIiwicm9sZSI6IlNUVURFTlQiLCJpYXQiOjE3NTM0Nzc5MDEsImV4cCI6MTc1MzU2NDMwMX0.spPj2NFobTNZtkijPnv2Vh98NyIpj9pe_328XJqlEqk
Content-Type: application/json

### get post by type (general)
GET http://localhost:3000/post/general
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1MzYwMjk2MCwiZXhwIjoxNzUzNjg5MzYwfQ.8GC-pDnL8GMzQOwjbiZaPMWF15CEdCygAXVYgEgJl1o
Content-Type: application/json

### get post by type (academic)
GET http://localhost:3000/post/academic
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1MzU3MjkxMCwiZXhwIjoxNzUzNjU5MzEwfQ.uTdgUX6gV1UnpgNSO-32VIIyqxuSF5Gk8JXwFIlitFk
Content-Type: application/json

### get post by type (resource)
GET http://localhost:3000/post/resource
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1MzYwMjk2MCwiZXhwIjoxNzUzNjg5MzYwfQ.8GC-pDnL8GMzQOwjbiZaPMWF15CEdCygAXVYgEgJl1o
Content-Type: application/json

### get post by type (opportunity)
GET http://localhost:3000/post/opportunity
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1MzYwMjk2MCwiZXhwIjoxNzUzNjg5MzYwfQ.8GC-pDnL8GMzQOwjbiZaPMWF15CEdCygAXVYgEgJl1o
Content-Type: application/json


### get trending posts
GET http://localhost:3000/post/trending
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1NDUwNTE3MSwiZXhwIjoxNzU0NTkxNTcxfQ.82eia1TNhafaRiQrTh2wlYoGsyuYSpCS6RsYft8o0XE
Content-Type: application/json

### get posts by user
GET http://localhost:3000/post/user/146ba0b7-e513-418d-89dd-539ffec59a04
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1NDY3ODcwMSwiZXhwIjoxNzU0NzY1MTAxfQ.x_RZeE2k8u88mim52Atd2C6ulvXnhNrkZfKOToWthnY


### flag a post
POST  http://localhost:3000/post/9010854c-c0d0-483a-bb95-92efb3d11ab0/flag
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjQ2OTA4My1mNTM0LTQxZDItODE3Ni1jMWIxMDdlYzNjNjMiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpMTZAZ21haWwuY29tIiwicm9sZSI6IlNUVURFTlQiLCJpYXQiOjE3NTg3NTcyODYsImV4cCI6MTc1ODg0MzY4Nn0.Gg7RsGmB9OIdt5dZCgpf0JD9IP3FhzzttRjKDtel_bk
Content-Type: application/json

{
  "reason": "This post has not is causing confusion"
}
