
### create a profile
POST http://localhost:3000/profiles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjQ2OTA4My1mNTM0LTQxZDItODE3Ni1jMWIxMDdlYzNjNjMiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpMTZAZ21haWwuY29tIiwicm9sZSI6IlNUVURFTlQiLCJpYXQiOjE3NTMzOTE3MjAsImV4cCI6MTc1MzQ3ODEyMH0.jO9kPLzVhQPK1p8N5knxTBiKfWlr-fzeHN_RDVVxYHc

{
  "name": "Dee Winnie",
  "institution": "Meru University",
  "academicLevel": "Year 3",
  "bio": "AGED and poultry farmer",
  "skills": ["Poultry", "Singing", "Farming"],
  "profileImage": "https://res.cloudinary.com/academeet/image/upload/v17123456/academeet/users/profiles/xy123z.png",
  "interests": ["coding", "AI", "QA & QE"]
}

### get a profile by user id
GET http://localhost:3000/profiles/f82434e2-1b6c-42ba-a8e2-f6413861650c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmU1YmY0OC0zMzQzLTRhZDMtODcwNi1kMjVhOTM5Y2E3ZWQiLCJlbWFpbCI6ImoyNjUxNTc2MkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1MzI5NTUyMywiZXhwIjoxNzUzMzgxOTIzfQ.3_oRf6143X27wuH9k3TZlMKeu6NJfKxEgFy3yX8nLEg

### update a profile by user id
PATCH http://localhost:3000/profiles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjQ2OTA4My1mNTM0LTQxZDItODE3Ni1jMWIxMDdlYzNjNjMiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpMTZAZ21haWwuY29tIiwicm9sZSI6IlNUVURFTlQiLCJpYXQiOjE3NTMzOTE3MjAsImV4cCI6MTc1MzQ3ODEyMH0.jO9kPLzVhQPK1p8N5knxTBiKfWlr-fzeHN_RDVVxYHc

{
  "course": "AGED"
}

### 
GET http://localhost:3000/profiles/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmU1YmY0OC0zMzQzLTRhZDMtODcwNi1kMjVhOTM5Y2E3ZWQiLCJlbWFpbCI6ImoyNjUxNTc2MkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1MzI5NTg4NCwiZXhwIjoxNzUzMzgyMjg0fQ.eZSGrb84WchkI5JIDo7W403uMD9eVWG7BdQJEh3bsic