// Endpoint for recommend()
GET http://localhost:3000/recommendations/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1MzU3MjkxMCwiZXhwIjoxNzUzNjU5MzEwfQ.uTdgUX6gV1UnpgNSO-32VIIyqxuSF5Gk8JXwFIlitFk
Content-Type: application/json

###
 // Endpoint for recommendSimilarPosts()
GET http://localhost:3000/recommendations/post/3ba78d59-1018-4af9-ba2d-7bc70284003a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDZiYTBiNy1lNTEzLTQxOGQtODlkZC01MzlmZmVjNTlhMDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc1MzU3MjkxMCwiZXhwIjoxNzUzNjU5MzEwfQ.uTdgUX6gV1UnpgNSO-32VIIyqxuSF5Gk8JXwFIlitFk
Content-Type: application/json