GET http://localhost:3000/recommendations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjQ2OTA4My1mNTM0LTQxZDItODE3Ni1jMWIxMDdlYzNjNjMiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpMTZAZ21haWwuY29tIiwicm9sZSI6IlNUVURFTlQiLCJpYXQiOjE3NTM0MDExMzUsImV4cCI6MTc1MzQ4NzUzNX0.Snp_mWhI_0PucFIGgEiFaMdjeaGTy5jMv9Q07SzMPoc
Content-Type: application/json
